# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

production:
  secret_key_base: dbcb58547a94f77c3960a6f883f7ee2230e3214aab336118211422de4011e535be3a8756182b5b671fcbcf9d1243e3b77875ea474becb61d29affcf0cbb950aa

development:
  secret_key_base: dbcb58547a94f77c3960a6f883f7ee2230e3214aab336118211422de4011e535be3a8756182b5b671fcbcf9d1243e3b77875ea474becb61d29affcf0cbb950aa

test:
  secret_key_base: 06559894624030dc4140f4cbad2857a2d0b08045c0e97761a6af4f951d99d9293c014844db2a1497a51bdfc0d262adf1870b684c74e046f8564c791b7a00e165

# Do not keep production secrets in the repository,
# instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
